payara/Payara-Enterprise-Documentation

- docs/modules/ROOT/pages/documentation/microprofile/config.adoc
In connection with payara/Payara#4614
A copy of https://github.com/payara/Payara-Server-Documentation/pull/730
> APPSERV-114 adds section on added caching

- docs/modules/ROOT/pages/documentation/microprofile/config.adoc
- docs/modules/ROOT/pages/documentation/payara-server/server-configuration/var-substitution/usage-of-variables.adoc
Original PR: payara/Payara#4584
Copy of https://github.com/payara/Payara-Server-Documentation/pull/724
> APPSERV-20 Document new payara expression config source

- docs/modules/ROOT/pages/documentation/user-guides/monitoring/monitoring-console.adoc
In connection with: payara/monitoring-console#8.
A copy of payara/Payara-Server-Documentation#738
> APPSERV-146 add paragraph on bookmarkable URLs

- docs/modules/ROOT/pages/documentation/payara-server/asadmin-commands/misc-commands.adoc
- docs/modules/ROOT/pages/documentation/payara-server/server-configuration/http/network-listeners.adoc
Enterprise edition of https://github.com/payara/Payara-Community-Documentation/pull/30
Only change is version mentioned is the enterprise version.
> APPSERV-152 Adds section on the restart-http-listeners command

- docs/modules/ROOT/nav.adoc
- docs/modules/ROOT/pages/documentation/payara-server/server-configuration/certificate-management.adoc
- docs/modules/ROOT/pages/documentation/payara-server/server-configuration/ssl-certificates.adoc
Title.
Also adjusted the existing SSL-Certificates page to reference new commands.
> APPSERV-149 APPSERV-150 APPSERV-151 APPSERV-153 Integrated certificate management documentation

- docs/modules/ROOT/pages/schemas/README.adoc
This is already in 5.20.0, porting to master
> Fix links to schemas

- docs/modules/ROOT/pages/documentation/microprofile/README.adoc
- docs/modules/ROOT/pages/documentation/microprofile/faulttolerance.adoc
Small updates to maintain version consistency
> Minor fixes to replace 5.202 versioning

- docs/modules/ROOT/pages/documentation/payara-micro/appendices/cmd-line-opts.adoc
- docs/modules/ROOT/pages/documentation/payara-micro/configuring/config-sys-props.adoc
Code change: https://github.com/payara/Payara-Enterprise/pull/103
Community Doc PR: https://github.com/payara/Payara-Community-Documentation/pull/44
> FISH-205 Document Dynamic Logging

- docs/modules/ROOT/pages/documentation/payara-server/server-configuration/certificate-management.adoc
> FISH-195 Add nodedir and node options to certificate management commands

- docs/modules/ROOT/nav.adoc
- docs/modules/ROOT/pages/documentation/payara-server/server-configuration/security/README.adoc
- docs/modules/ROOT/pages/documentation/payara-server/server-configuration/security/multiple-mechanism-in-ear.adoc
Community PR: https://github.com/payara/Payara-Community-Documentation/pull/46
> FISH-171: Multiple HttpAuthenticationMechanism in EAR

- docs/modules/ROOT/pages/documentation/payara-server/server-configuration/http/protocols/ssl-options.adoc
Comm PR: https://github.com/payara/Payara-Community-Documentation/pull/58
> FISH-314 [Enterprise] Document new TLS 1.3 support

- docs/modules/ROOT/pages/documentation/user-guides/monitoring/monitoring-console.adoc
In connection with: https://github.com/payara/Payara-Enterprise/pull/154
> FISH-277 Updates MC sections after Admin GUI Integration

- docs/modules/ROOT/pages/jakartaee-certification/5.20.0/tck-results-full-5.20.0.adoc
(The previous one was justa copy of 5.201 TCK summary)
> Updated 5.20.0 TCK summary

- docs/modules/ROOT/pages/documentation/ecosystem/arquillian-containers/README.adoc
- docs/modules/ROOT/pages/documentation/ecosystem/cloud-connectors/README.adoc
- docs/modules/ROOT/pages/documentation/ecosystem/eclipse-plugin.adoc
- docs/modules/ROOT/pages/documentation/ecosystem/vscode-extension/README.adoc
- docs/modules/ROOT/pages/documentation/payara-micro/maven/maven.adoc
- docs/modules/ROOT/pages/documentation/payara-server/health-check-service/asadmin-commands.adoc
- docs/modules/ROOT/pages/documentation/payara-server/public-api/openid-connect-support.adoc
- docs/modules/ROOT/pages/documentation/payara-server/public-api/roles-permitted.adoc
- docs/modules/ROOT/pages/documentation/payara-server/server-configuration/security/README.adoc
- docs/modules/ROOT/pages/documentation/payara-server/server-configuration/security/multiple-mechanism-in-ear.adoc
- docs/modules/ROOT/pages/documentation/user-guides/monitoring/enable-jmx-monitoring.adoc
- docs/modules/ROOT/pages/documentation/user-guides/monitoring/mbeans.adoc
- docs/modules/ROOT/pages/documentation/user-guides/using-the-maven-cargo-plugin.adoc
Version for Enterprise of this community PR https://github.com/payara/Payara-Community-Documentation/pull/64
> Correction to external links

- docs/modules/ROOT/pages/documentation/payara-server/h2/h2.adoc
Original Comm PR: https://github.com/payara/Payara-Community-Documentation/pull/65
> How to connect to H2 with SQL manager

- docs/modules/ROOT/nav.adoc
- docs/modules/ROOT/pages/jakartaee-certification/5.20.0/README.adoc
- docs/modules/ROOT/pages/jakartaee-certification/5.20.0/tck-results-full-5.20.0.adoc
- docs/modules/ROOT/pages/jakartaee-certification/README.adoc
Copied from the 5.20.0 branch (PR #44)
> TCK summary for 5.20.0

- docs/modules/ROOT/pages/documentation/payara-server/logging/json-formatter.adoc
> FISH-141 Support Additional Fields with LogRecord when using JsonLogFormatter

- docs/modules/ROOT/pages/documentation/payara-server/app-deployment/deployment-descriptors.adoc
- docs/modules/ROOT/pages/documentation/payara-server/jdbc/log-jdbc-calls.adoc
Payara Enterprise PR payara/payara-enterprise#189
> Document log-jdbc-calls now available via asadmin and payara-resources.xml

- docs/modules/ROOT/pages/documentation/payara-server/server-configuration/jvm-options.adoc
Signed-off-by: Andrew Pielage <andrew.pielage@payara.fish>
Community PR: https://github.com/payara/Payara-Community-Documentation/pull/77
> FISH-508 Add section on deleting JVM options

- docs/modules/ROOT/nav.adoc
- docs/modules/ROOT/pages/documentation/payara-server/request-tracing-service/request-tracing-service.adoc
- docs/modules/ROOT/pages/documentation/payara-server/request-tracing-service/tracing-remote-ejbs.adoc
- docs/modules/ROOT/pages/documentation/payara-server/request-tracing-service/usage.adoc
Port of https://github.com/payara/Payara-Community-Documentation/pull/54
> FISH-369 FISH-244 Document Tracing of Remote EJBs

- docs/modules/ROOT/nav.adoc
- docs/modules/ROOT/pages/documentation/ecosystem/docker-images.adoc
- docs/modules/ROOT/pages/documentation/ecosystem/docker-micro-usage.adoc
- docs/modules/ROOT/pages/documentation/ecosystem/docker-server-usage.adoc
Enterprise version of https://github.com/payara/Payara-Community-Documentation/pull/74
Only docker-images.adoc is slightly different.
> Docker Image usage documentation.

- docs/modules/ROOT/nav.adoc
- docs/modules/ROOT/pages/documentation/payara-server/server-configuration/certificate-management.adoc
- docs/modules/ROOT/pages/release-notes/release-notes-22-0.adoc
- docs/modules/ROOT/pages/security/security-fix-list.adoc
> Update 5.22 with the TCK summary

- docs/modules/ROOT/pages/documentation/payara-server/jpa-cache-coordination.adoc
Wasn't valid according to the XSD schema
> Fix of example code

- docs/modules/ROOT/nav.adoc
- docs/modules/ROOT/pages/jakartaee-certification/5.23.0/README.adoc
- docs/modules/ROOT/pages/jakartaee-certification/5.23.0/tck-results-full-5.23.0.adoc
> FISH-724 Jakarta TCK Results for Payara Server 5.23.0

- docs/modules/ROOT/nav.adoc
- docs/modules/ROOT/pages/release-notes/README.adoc
- docs/modules/ROOT/pages/release-notes/release-notes-23-0.adoc
> FISH-725 Release Notes 5.23.0

- docs/modules/ROOT/pages/documentation/user-guides/monitoring/monitoring-console.adoc
Documentation in connection with https://github.com/payara/monitoring-console/pull/28
> FISH-481 Documents new InSight Page Settings 'Fill Empty Cells'

- docs/modules/ROOT/nav.adoc
- docs/modules/ROOT/pages/jakartaee-certification/5.23.0/README.adoc
- docs/modules/ROOT/pages/jakartaee-certification/5.23.0/tck-results-web-5.23.0.adoc
> FISH-495 Web Profile Jakarta TCK results

- docs/modules/ROOT/pages/documentation/payara-micro/configuring/config-keystores.adoc
Community: https://github.com/payara/Payara-Community-Documentation/pull/105
> Note about `add-pkcs8` and `add-to-keystore` in Payara Micro

- docs/modules/ROOT/pages/documentation/payara-server/app-deployment/deployment-descriptors.adoc
Antora has no global variable replacement for code blocks, meaning it has to be done strictly above the code block.
Community PR: https://github.com/payara/Payara-Community-Documentation/pull/117
> SERV-502 Variable repacement in code example is not working (Enterprise)

- docs/modules/ROOT/nav.adoc
- docs/modules/ROOT/pages/jakartaee-certification/5.23.1/README.adoc
- docs/modules/ROOT/pages/jakartaee-certification/5.23.1/tck-results-full-5.23.1.adoc
- docs/modules/ROOT/pages/jakartaee-certification/5.23.1/tck-results-web-5.23.1.adoc
> [FISH-808] - Enterprise Jakarta Certification

- docs/modules/ROOT/pages/documentation/ecosystem/arquillian-containers/payara-micro-managed.adoc
- docs/modules/ROOT/pages/documentation/ecosystem/arquillian-containers/payara-server-embedded.adoc
- docs/modules/ROOT/pages/documentation/ecosystem/arquillian-containers/payara-server-managed.adoc
- docs/modules/ROOT/pages/documentation/ecosystem/arquillian-containers/payara-server-remote.adoc
Fixes: https://github.com/payara/Payara-Community-Documentation/issues/45
> SERV-542 Examples shown in the arquillian containers not working

- docs/modules/ROOT/pages/documentation/payara-server/jaxws/README.adoc
- docs/modules/ROOT/pages/documentation/payara-server/jbatch/jbatch.adoc
- docs/modules/ROOT/pages/documentation/payara-server/jcache/jcache.adoc
- docs/modules/ROOT/pages/documentation/payara-server/server-configuration/var-substitution/README.adoc
so that it doesn't appear we have no detailed documentation.
Community PR (already approved and merged) https://github.com/payara/Payara-Community-Documentation/pull/123
> Additional links

- docs/antora.yml
- docs/modules/ROOT/nav.adoc
- docs/modules/ROOT/pages/release-notes/README.adoc
- docs/modules/ROOT/pages/release-notes/release-notes-24-0.adoc
Release notes for Payara Enterprise 5.24.0 Release - Pending completion of Jakarta TCK to see if anything will need pulling out
> [FISH-920] - Payara 5.24.0 Release Notes

- docs/modules/ROOT/nav.adoc
- docs/modules/ROOT/pages/jakartaee-certification/5.24.0/README.adoc
- docs/modules/ROOT/pages/jakartaee-certification/5.24.0/tck-results-full-5.24.0.adoc
- docs/modules/ROOT/pages/jakartaee-certification/5.24.0/tck-results-web-5.24.0.adoc
Results of the TCK against Enterprise 5.24.0 on Full and Web Profiles
> [FISH-920] - Jakarta TCK Certification Results

- docs/modules/ROOT/pages/general-info/general-info.adoc
Update to the Payara Enterprise's release strategy messaging and a minor CVE update missed from the previous releases.
> Update to Payara Enterprise Messaging + Missing CVE

- docs/modules/ROOT/pages/security/security-fix-list.adoc
Fixed weird merge conflict lines introduced in last PR
> Fixed merge conflict lines

- docs/modules/ROOT/pages/general-info/general-info.adoc
Consistent messaging update for release strategy in all versions
> Update to Enterprise release strategy messaging

- docs/modules/ROOT/pages/general-info/supported-platforms.adoc
Reverts payara/Payara-Enterprise-Documentation#96
> Revert "Remove claim of supporting OpenJ9"

- docs/modules/ROOT/pages/documentation/payara-server/upgrade-server.adoc
`rollback-server` now restores most recent backup
> FISH-982 Document rollback-server change

- docs/modules/ROOT/pages/documentation/payara-server/ejb/persistent-timers.adoc
Timers can now be migrated from live instances.
> FISH-105 Document change in migrate-timers

- docs/antora.yml
- docs/modules/ROOT/nav.adoc
- docs/modules/ROOT/pages/release-notes/README.adoc
- docs/modules/ROOT/pages/release-notes/release-notes-25-0.adoc
Release Notes for Payara 5.25.0 Enterprise Edition
TCK Results will come later as a separate PR
> [FISH-1045] - Payara 5.25.0 Release Notes

- docs/modules/ROOT/nav.adoc
- docs/modules/ROOT/pages/jakartaee-certification/5.25.0/README.adoc
- docs/modules/ROOT/pages/jakartaee-certification/5.25.0/tck-results-full-5.25.0.adoc
- docs/modules/ROOT/pages/jakartaee-certification/5.25.0/tck-results-web-5.25.0.adoc
- docs/modules/ROOT/pages/jakartaee-certification/README.adoc
Jakarta EE TCK Results for Payara Enterprise 5.25.0 Release
Pending confirmation of potential bug before merge can be made
> [FISH-1045] - Payara Enterpruse 5.25.0 TCK Results

- docs/modules/ROOT/pages/documentation/payara-server/server-configuration/var-substitution/types-of-variables.adoc
Community PR: https://github.com/payara/Payara-Community-Documentation/pull/134/files
> FISH-992 document default value option in variable substitution

- docs/modules/ROOT/pages/documentation/payara-server/notification-service/notification-service.adoc
- docs/modules/ROOT/pages/documentation/payara-server/notification-service/notifiers/event-bus-notifier.adoc
Community PR: https://github.com/payara/Payara-Community-Documentation/pull/136
> Clean up documentation

- docs/modules/ROOT/pages/documentation/payara-server/notification-service/asadmin-commands.adoc
- docs/modules/ROOT/pages/documentation/payara-server/notification-service/notifiers.adoc
- docs/modules/ROOT/pages/documentation/payara-server/notification-service/notifiers/cdi-event-bus-notifier.adoc
- docs/modules/ROOT/pages/documentation/payara-server/notification-service/notifiers/datadog-notifier.adoc
- docs/modules/ROOT/pages/documentation/payara-server/notification-service/notifiers/email-notifier.adoc
- docs/modules/ROOT/pages/documentation/payara-server/notification-service/notifiers/event-bus-notifier.adoc
- docs/modules/ROOT/pages/documentation/payara-server/notification-service/notifiers/hipchat-notifier.adoc
- docs/modules/ROOT/pages/documentation/payara-server/notification-service/notifiers/jms-notifier.adoc
- docs/modules/ROOT/pages/documentation/payara-server/notification-service/notifiers/log-notifier.adoc
- docs/modules/ROOT/pages/documentation/payara-server/notification-service/notifiers/newrelic-notifier.adoc
- docs/modules/ROOT/pages/documentation/payara-server/notification-service/notifiers/slack-notifier.adoc
- docs/modules/ROOT/pages/documentation/payara-server/notification-service/notifiers/snmp-notifier.adoc
- docs/modules/ROOT/pages/documentation/payara-server/notification-service/notifiers/xmpp-notifier.adoc
Reverts payara/Payara-Enterprise-Documentation#121
Not making this release.
> Revert "FISH-468 Notifiers Documentation Port"

- docs/modules/ROOT/pages/documentation/payara-server/upgrade-server.adoc
Title.
Documentation for https://github.com/payara/Payara-Enterprise/pull/309 and https://github.com/payara/Payara-Enterprise/pull/311
> FISH-962 FISH-979 Document Windows Support and Domaindirs Parameter

- docs/modules/ROOT/pages/documentation/payara-server/upgrade-server.adoc
Removes the caution blocks.
Main PR: https://github.com/payara/Payara-Enterprise/pull/339
> FISH-1145 Add Validation to Upgrade Tool Scripts to Help Prevent Incorrect Usage

- docs/modules/ROOT/pages/documentation/payara-micro/appendices/cmd-line-opts.adoc
Port of https://github.com/payara/Payara-Community-Documentation/pull/141
> FISH-1191 Document Payara Micro --nocluster option disables Hazlecast

- docs/antora.yml
- docs/modules/ROOT/nav.adoc
- docs/modules/ROOT/pages/jakartaee-certification/5.27.0/README.adoc
- docs/modules/ROOT/pages/jakartaee-certification/5.27.0/tck-results-full-5.27.0.adoc
- docs/modules/ROOT/pages/jakartaee-certification/5.27.0/tck-results-web-5.27.0.adoc
- docs/modules/ROOT/pages/release-notes/README.adoc
- docs/modules/ROOT/pages/release-notes/release-notes-27-0.adoc
TCK results to come in later PR
> [FISH-1259] - Payara 5.27.0 Release Notes

- docs/modules/ROOT/pages/documentation/payara-server/upgrade-server.adoc
Upgrade Tool is moving out of MVP.
> Remove MVP

- docs/modules/ROOT/pages/documentation/ecosystem/cloud-connectors/README.adoc
- docs/modules/ROOT/pages/documentation/ecosystem/gradle-plugin.adoc
- docs/modules/ROOT/pages/documentation/ecosystem/maven-plugin.adoc
- docs/modules/ROOT/pages/documentation/ecosystem/security-connectors.adoc
- docs/modules/ROOT/pages/documentation/payara-micro/maven/maven.adoc
- docs/modules/ROOT/pages/documentation/payara-server/README.adoc
- docs/modules/ROOT/pages/documentation/payara-server/docker/docker-nodes.adoc
- docs/modules/ROOT/pages/documentation/payara-server/ejb/lite-remote-ejb.adoc
- docs/modules/ROOT/pages/documentation/payara-server/rest-monitoring/using-rest-monitoring.adoc
Plus a couple of minor fixes to improve readability
> Improvements on attribute substitution for current platform version

- docs/antora.yml
- docs/modules/ROOT/nav.adoc
- docs/modules/ROOT/pages/jakartaee-certification/5.28.0/README.adoc
- docs/modules/ROOT/pages/jakartaee-certification/5.28.0/tck-results-full-5.28.0.adoc
- docs/modules/ROOT/pages/jakartaee-certification/5.28.0/tck-results-web-5.28.0.adoc
- docs/modules/ROOT/pages/release-notes/README.adoc
- docs/modules/ROOT/pages/release-notes/release-notes-28-0.adoc
> 5.28.0 Release Notes

- docs/modules/ROOT/pages/documentation/payara-server/server-configuration/http/protocols/ssl-options.adoc
Document the new HSTS options
Port of https://github.com/payara/Payara-Community-Documentation/pull/155 and https://github.com/payara/Payara-Community-Documentation/pull/160.
> FISH-1021 - HSTS

- docs/modules/ROOT/pages/README.adoc
Marketing has noted some people are not aware of what Payara Platform means
Community PR:
https://github.com/payara/Payara-Community-Documentation/pull/161
> SERV-602 Clarify what Payara Platform means in Documentation README

- docs/antora.yml
- docs/modules/ROOT/nav.adoc
- docs/modules/ROOT/pages/jakartaee-certification/5.28.1/README.adoc
- docs/modules/ROOT/pages/jakartaee-certification/5.28.1/tck-results-full-5.28.1.adoc
- docs/modules/ROOT/pages/jakartaee-certification/5.28.1/tck-results-web-5.28.1.adoc
- docs/modules/ROOT/pages/release-notes/README.adoc
- docs/modules/ROOT/pages/release-notes/release-notes-28-1.adoc
> [FISH-1390] Payara 5.28.1 Release Notes

- docs/modules/ROOT/pages/security/security-fix-list.adoc
Community PR: https://github.com/payara/Payara-Community-Documentation/pull/190
> FISH-1421 Security fix

- docs/modules/ROOT/pages/documentation/microprofile/metrics/vendor-metrics.adoc
- docs/modules/ROOT/pages/documentation/payara-server/app-deployment/deployment-descriptors.adoc
Community PR: https://github.com/payara/Payara-Community-Documentation/pull/189
> 5.29 improvements

- docs/modules/ROOT/nav.adoc
- docs/modules/ROOT/pages/jakartaee-certification/5.29.0/README.adoc
- docs/modules/ROOT/pages/jakartaee-certification/5.29.0/tck-results-full-5.29.0.adoc
- docs/modules/ROOT/pages/jakartaee-certification/5.29.0/tck-results-web-5.29.0.adoc
> Enterprise 5.29.0 TCK Results

- docs/modules/ROOT/pages/security/security.adoc
Reworded security information with a simplified message for Payara Enterprise customers
> Reworded security info

- docs/modules/ROOT/pages/general-info/supported-platforms.adoc
[SERV-664] Update Supported Platforms Page
[SERV-644]: https://payara.atlassian.net/browse/SERV-644
[SERV-664]: https://payara.atlassian.net/browse/SERV-664
> SERV-664 Update Supported Platforms Page

- docs/antora.yml
- docs/modules/ROOT/nav.adoc
- docs/modules/ROOT/pages/jakartaee-certification/5.30.0/README.adoc
- docs/modules/ROOT/pages/jakartaee-certification/5.30.0/tck-results-full-5.30.0.adoc
- docs/modules/ROOT/pages/jakartaee-certification/5.30.0/tck-results-web-5.30.0.adoc
- docs/modules/ROOT/pages/release-notes/release-notes-30-0.adoc
> [QACI-5504] - 5.30.0 Release Notes + TCK Results

- docs/modules/ROOT/pages/documentation/payara-server/public-api/openid-connect-support.adoc
Community PR: https://github.com/payara/Payara-Community-Documentation/pull/191
Also copied the section "Logout Functionality" from Community, which was missing in Enterprise (added to 5.22.0 with FISH-433)
> FISH-385 Multitenant OpenID Connect

- docs/modules/ROOT/pages/documentation/payara-server/public-api/openid-connect-support.adoc
Community PR: https://github.com/payara/Payara-Community-Documentation/pull/238
> FISH-384 OpenID Connect Bearer Auth

- docs/modules/ROOT/pages/documentation/payara-server/server-configuration/ssl-certificates.adoc
Updated Additional Keystore information to be accurate with delimiter changes.
Enterprise PR: https://github.com/payara/Payara-Enterprise/pull/452
> FISH-5693 Updated multiple keystore delimiter to be OS dependent

- docs/modules/ROOT/nav.adoc
- docs/modules/ROOT/pages/documentation/payara-server/Payara Server Upgrade Tool.adoc
> SERV-670 Update documentation with Upgrade Tool name v5.30

- docs/modules/ROOT/nav.adoc
- docs/modules/ROOT/pages/documentation/payara-server/Payara Server Upgrade Tool.adoc
> SERV-670 Update documentation with Upgrade Tool name v5.29

- docs/modules/ROOT/nav.adoc
- docs/modules/ROOT/pages/documentation/payara-server/Payara Server Upgrade Tool.adoc
> SERV-670 Update documentation with Upgrade Tool name v5.28

- docs/modules/ROOT/nav.adoc
- docs/modules/ROOT/pages/documentation/payara-server/Payara Server Upgrade Tool.adoc
> SERV-670 Update documentation with Upgrade Tool name v5.27

- docs/modules/ROOT/nav.adoc
- docs/modules/ROOT/pages/documentation/payara-server/Payara Server Upgrade Tool.adoc
> SERV-670 Update documentation with Upgrade Tool name v5.26

- docs/modules/ROOT/nav.adoc
- docs/modules/ROOT/pages/documentation/payara-server/Payara Server Upgrade Tool.adoc
> SERV-670 Update documentation with Upgrade Tool name v5.25

- docs/modules/ROOT/nav.adoc
- docs/modules/ROOT/pages/documentation/payara-server/Payara Server Upgrade Tool.adoc
> SERV-670 Update documentation with Upgrade Tool name v5.24

- docs/modules/ROOT/pages/documentation/microprofile/metrics/vendor-metrics.adoc
- docs/modules/ROOT/pages/security/security-fix-list.adoc
Plus a fix in an unrelated code example
> Added security fixes for the upcoming release

- docs/modules/ROOT/nav.adoc
- docs/modules/ROOT/pages/documentation/payara-server/server-configuration/security/README.adoc
- docs/modules/ROOT/pages/documentation/payara-server/server-configuration/security/certificate-realm-certificate-validation.adoc
Backport to the recently released version
> FISH-5646: Certificate Validation API into 5.31 branch

- docs/modules/ROOT/pages/documentation/payara-server/server-configuration/http/protocols/http-options.adoc
HTTP Compression Level and Strategy documentation
Enterprise PR: https://github.com/payara/Payara-Enterprise/pull/474
> FISH-376 Allow configuration details of HTTP GZIP compression

- docs/modules/ROOT/pages/documentation/ecosystem/gradle-plugin.adoc
- docs/modules/ROOT/pages/documentation/ecosystem/maven-plugin.adoc
Community PR : https://github.com/payara/Payara-Community-Documentation/pull/236
> Hot Deploy feature added to Payara Micro Build tool plugins

- docs/modules/ROOT/pages/documentation/payara-server/asadmin-commands/server-management-commands.adoc
Documentation for create-service and _delete-service; based on man pages, added SystemD Linux support.
> Fish 5785 create systemd service documentation

- docs/modules/ROOT/pages/documentation/payara-server/hazelcast/configuration.adoc
- docs/modules/ROOT/pages/release-notes/release-notes-32-0.adoc
Also updated in the 5.32 branch
> SERV-692 Note about dropping --clusterPassword

- docs/modules/ROOT/pages/documentation/payara-server/public-api/openid-connect-support.adoc
Community PR: https://github.com/payara/Payara-Community-Documentation/pull/273
> SERV-654 Note about escaping baseURL variable

- docs/modules/ROOT/pages/documentation/microprofile/rest-client.adoc
Title.
Related PRs:
* https://github.com/payara/MicroProfile-TCK-Runners/pull/156
* https://github.com/payara/patched-src-jersey/pull/111
* https://github.com/payara/Payara-Enterprise/pull/513
> FISH-1519 Document MP Rest Client Proxy Config

- docs/modules/ROOT/pages/documentation/payara-server/public-api/openid-connect-support.adoc
Adding doc for new property disableScopeValidation
> FISH-386: scope validation property doc

- docs/modules/ROOT/pages/documentation/payara-server/public-api/openid-connect-support.adoc
Documentation for OpenIdProviderMetadata annotation accompanying PR https://github.com/payara/ecosystem-security-connectors/pull/138
> FISH-5743 add providerMetadata documentation

- docs/modules/ROOT/pages/documentation/payara-server/public-api/openid-connect-support.adoc
Document the new OpenId configuration, add note, that key may repeat.
> FISH-5745 document extraParams microprofile config

- docs/modules/ROOT/pages/security/security-fix-list.adoc
Same as https://github.com/payara/Payara-Community-Documentation/pull/285 in Community.
> H2 Console Vulnerability

- docs/modules/ROOT/pages/documentation/ecosystem/arquillian-containers/payara-server-embedded.adoc
Main PR: https://github.com/payara/ecosystem-arquillian-connectors/pull/163
Signed-off-by: Andrew Pielage <pandrex247@hotmail.com>
> FISH-778 Document Embedded Arquillian Server System Properties

- docs/modules/ROOT/nav.adoc
- docs/modules/ROOT/pages/jakartaee-certification/5.36.0/README.adoc
- docs/modules/ROOT/pages/jakartaee-certification/5.36.0/tck-results-full-5.36.0.adoc
- docs/modules/ROOT/pages/jakartaee-certification/5.36.0/tck-results-web-5.36.0.adoc
- docs/modules/ROOT/pages/release-notes/README.adoc
- docs/modules/ROOT/pages/release-notes/release-notes-36-0.adoc
> 5.36.0 release notes tck results

- docs/modules/ROOT/nav.adoc
Updating the nav.adoc file was missed in https://github.com/payara/Payara-Enterprise-Documentation/pull/209
> FISH-230 Update Nav

- docs/modules/ROOT/nav.adoc
- docs/modules/ROOT/pages/jakartaee-certification/5.37.0/README.adoc
- docs/modules/ROOT/pages/jakartaee-certification/5.37.0/tck-results-full-5.37.0.adoc
- docs/modules/ROOT/pages/jakartaee-certification/5.37.0/tck-results-web-5.37.0.adoc
- docs/modules/ROOT/pages/microprofile-certification/5.37.0/README.adoc
- docs/modules/ROOT/pages/microprofile-certification/5.37.0/microprofile-4.1-tck-results-full-5.37.0.adoc
- docs/modules/ROOT/pages/microprofile-certification/5.37.0/microprofile-4.1-tck-results-web-5.37.0.adoc
- docs/modules/ROOT/pages/microprofile-certification/README.adoc
TCK Results for Jakarta EE & MicroProfile for Payara Server 5.37.0
Incorporates work by Cuba from https://github.com/payara/Payara-Enterprise-Documentation/pull/232
> Jakarta EE & MicroProfile TCK Results 5.37.0

- docs/modules/ROOT/nav.adoc
- docs/modules/ROOT/pages/release-notes/README.adoc
- docs/modules/ROOT/pages/release-notes/release-notes-37-0.adoc
Signed-off-by: Andrew Pielage <pandrex247@hotmail.com>
> 5.37.0 Release Notes

- docs/modules/ROOT/nav.adoc
- docs/modules/ROOT/pages/microprofile-certification/5.36.0/README.adoc
- docs/modules/ROOT/pages/microprofile-certification/5.36.0/microprofile-4.1-tck-results-full-5.36.0.adoc
- docs/modules/ROOT/pages/microprofile-certification/README.adoc
Required for MP Certification Request - needs review of format
> [QACI-645] - MicroProfile 4.1 Results Enterprise 5.36.0

- docs/modules/ROOT/pages/microprofile-certification/5.37.0/README.adoc
Improve formatting, and noticed a mistake
> MicroProfile TCK Results Formatting and Version Mistake

- docs/modules/ROOT/pages/documentation/ecosystem/docker-images/micro-image-overview.adoc
- docs/modules/ROOT/pages/documentation/ecosystem/docker-images/server-image-overview.adoc
Community PR: https://github.com/payara/Payara-Community-Documentation/pull/312
> FISH-6353 Document existence of JDK 17 Docker image
